version: "3.8"

services:
  master_players_dump:
    image: mrtolkien/master_players_dump
    env_file:
      - env/.env
    build:
      context: .
      target: master_players_dump_pro
    volumes:
    - type: bind
      source: ./dump
      target: /dump
